import Image from "next/image";
import { ArrowUpRight, ImageIcon } from "lucide-react";
import { FaGithub } from "react-icons/fa";
import type { Project } from "@/types";
import { AnimatedWords } from "./AnimatedText";
import { SpotlightCard } from "./reactbits/SpotlightCard";

export function ProjectCard({ project, index }: { project: Project; index: number }) {
  return <SpotlightCard className="card group flex h-full flex-col"><div className="project-preview relative aspect-[16/9] overflow-hidden rounded-t-[1.2rem] border-b border-white/[.08]"><span className="absolute left-5 top-5 z-10 text-xs font-semibold tracking-[.12em] text-white/45">0{index + 1}</span>{project.image ? <Image src={project.image} alt={`${project.title} preview`} fill sizes="(min-width: 768px) 50vw, 100vw" className="object-cover" /> : <div className="absolute inset-0 z-10 grid place-items-center"><div className="flex flex-col items-center gap-3 text-white/35"><span className="grid size-12 place-items-center rounded-full border border-white/10 bg-black/30 backdrop-blur"><ImageIcon size={19} /></span><span className="text-[.65rem] font-semibold uppercase tracking-[.14em]">Project preview</span></div></div>}{project.featured && <span className="absolute right-5 top-5 z-10 rounded-full border border-[#7fffd4]/25 bg-[#7fffd4]/10 px-3 py-1 text-[.6rem] font-bold uppercase tracking-[.14em] text-[#a8ffe2]">Featured</span>}</div><div className="flex flex-1 flex-col p-6 sm:p-7"><h3 className="max-w-md text-xl font-semibold leading-tight tracking-[-.035em] sm:text-2xl"><AnimatedWords text={project.title} /></h3><p className="mt-4 text-sm leading-6 text-[#999993]">{project.description}</p><div className="mt-5 flex flex-wrap gap-x-3 gap-y-2">{project.technologies.map((tech) => <span key={tech} className="text-[.68rem] font-semibold uppercase tracking-[.09em] text-[#7fffd4]">{tech}</span>)}</div><ul className="mt-6 space-y-2.5 border-t border-white/[.07] pt-5 text-sm text-[#8c8c86]">{project.features.slice(0, 3).map((feature) => <li className="flex gap-3" key={feature}><span className="mt-[.45rem] size-1 shrink-0 rounded-full bg-[#7fffd4]" />{feature}</li>)}</ul><div className="mt-auto flex flex-wrap items-center gap-5 pt-7 text-xs font-bold"><a href={project.githubUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 transition hover:text-[#7fffd4]"><FaGithub size={16} /> GitHub</a>{project.demoUrl && <a href={project.demoUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-full border border-white/10 px-3 py-2 transition hover:border-[#7fffd4]/40 hover:text-[#7fffd4]">Live demo <ArrowUpRight size={15} /></a>}</div></div></SpotlightCard>;
}
